image: node:latest

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - code-quality
  - test

cache:
  paths:
    - node_modules/

code_quality:
  stage: code-quality

unit_test:
  stage: test
  script:
    - yarn
    - yarn test