FROM node:16

ARG APP_ID
ARG PUBLIC_CLIENT_PASSWORD
ARG PUBLIC_STATS_SERVER

ENV NEXT_PUBLIC_APP_ID=${APP_ID}
ENV NEXT_PUBLIC_CLIENT_PASSWORD=${PUBLIC_CLIENT_PASSWORD}
ENV NEXT_PUBLIC_STATS_SERVER=${PUBLIC_STATS_SERVER}

WORKDIR /app/etdadmin_server
COPY . .
RUN yarn

RUN yarn build
CMD ["yarn", "start"]
