apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
  labels:
    app: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: sirily11/etd-remote-admin-server:pr-1
          ports:
            - containerPort: 8080
