name: conventional-pr
on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - edited
      - synchronize
jobs:
  label:
    runs-on: ubuntu-latest
    name: Lint PR
    steps:
      - name: label
        uses: action-runner/conventional-labeler@v1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}